version: '3.5'
services:
  api:
    image: krymancer/rinha-de-backend-2023-q3-rust
    hostname: api
    depends_on:
      - db
    ports:
      - "9999:1234"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
networks:
  default:
    driver: bridge
    name: network