version: '3.5'
services:
  db:
      image: postgres
      hostname: db
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: db
      volumes:
        - ./conf/postgres/:/docker-entrypoint-initdb.d/
      ports:
        - 5431:5432