version: '3.5'
services:
  db:
      image: postgres
      hostname: db
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USER: user
        POSTGRES_DB: db
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - 5432:5432