version: '3.5'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api
    depends_on:
      - db
    expose:
      - 9999
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'